version: "3"

services:
  db:
    image: postgres
    volumes:
      - /custom/mount:/var/lib/postgresql/data \
    environment:
      - POSTGRES_PASSWORD=aErB3G7bDFMWv=.JZCFr
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - db-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - db-network
  usoftware-bayer-back:
    build: .
    restart: always
    expose:
      - 3000
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_SYNC: "true"
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: aErB3G7bDFMWv=.JZCFr
      DB_DATABASE: postgres
      SECRET_KEY: jnh483hulwefkjs
      EXPIRES_IN: 60m
    networks:
      - db-network
networks: 
  db-network:
    driver: bridge